# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml
# Validated with: curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  # Overall project coverage settings
  status:
    project:
      default:
        # Require 70% overall project coverage
        target: 70%
        # Allow 3% drop from base branch (handles refactoring scenarios)
        threshold: 3%
        # Fail PR check if project coverage is below target
        informational: false

    # Patch coverage - enforces coverage on new/modified code
    patch:
      default:
        # Require 70% coverage on changed lines (explicit, not auto)
        # This MUST be a numeric value to override auto-target behavior
        target: 70%
        # Allow 5% threshold below target for security/logging code
        threshold: 5%
        # Fail PR check if patch coverage is below target
        informational: false

# Comment settings for PR
comment:
  # Post comment on PR with coverage report
  layout: "header, diff, flags, files"
  # Update existing comment instead of posting new ones
  behavior: default
  # Always require head and base coverage
  require_head: true
  require_base: true

# Flags matching what is uploaded in CI (build.yml uploads with flags: backend)
flags:
  backend:
    paths:
      - src/
    carryforward: true

# Ignore patterns - exclude test files from coverage measurement
ignore:
  - "**/*.test.ts"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/node_modules/**"
  - "**/dist/**"
